# Generated by Django 2.2 on 2019-04-29 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catergory_name', models.CharField(max_length=200)),
                ('category_scores', models.IntegerField()),
                ('Catergory', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contestant_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('judgename', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=200)),
                ('Report_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_of_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('catergory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Catergory')),
                ('constestant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contestant')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Events')),
                ('judge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('catergory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Catergory')),
                ('event_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Events')),
                ('score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Scores')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='Sched_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Schedule_of_events'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='Event_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Events'),
        ),
    ]
