# Generated by Django 2.2 on 2019-04-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190429_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_of_events',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
