# Generated by Django 2.2 on 2019-04-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_results_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='title',
        ),
        migrations.AddField(
            model_name='events',
            name='num_judges',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
